
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOL COLON COMMA COMMENT DEF DEFINITION DOT EQUAL IDENT INPUT LBRACKET LONGCOMMENT LPAREN MAPPING MATH MULTIPLE NEWLINE NUMBER PREFERENCE RBRACKET REQUIRED RPAREN SECTION STRING\n        program : program NEWLINE funcDef\n                | funcDef\n    \n        program : program NEWLINE prefBlock\n                | prefBlock\n                | notNeededBlock\n                | program NEWLINE notNeededBlock\n    \n        notNeededBlock : DEFINITION LPAREN error RPAREN\n                       | MAPPING LBRACKET error RBRACKET\n    funcDef : DEF IDENT LPAREN paramlist RPAREN LBRACKET stmtList RBRACKET\n            | DEF IDENT LPAREN RPAREN LBRACKET stmtList RBRACKET\n    prefBlock : PREFERENCE LBRACKET sectionblocklist RBRACKETsectionblocklist : sectionblock\n            | sectionblocklist NEWLINE sectionblocksectionblock : SECTION LPAREN STRING RPAREN LBRACKET blockparamlist RBRACKETblockparamlist : blockparamlist COMMA blockparam\n            | blockparamblockparam : INPUT STRING\n                | STRING\n                | MULTIPLE COLON BOOL\n                | REQUIRED COLON BOOLstmtList : stmtList NEWLINE stmt\n            | stmt \n            | stmtList stmtstmt : functionCall\n         | functionWithObjstmt : error NEWLINEfunctionCall : IDENT LPAREN paramlist RPAREN\n                | IDENT LPAREN RPARENfunctionCall : IDENT LPAREN error NEWLINEfunctionWithObj : IDENT DOT functionCallfunctionWithObj : IDENT DOT error NEWLINEparamlist : paramlist COMMA param\n                | paramparam : identparam\n            | strparam\n            | numparam identparam : IDENT\n                | IDENT NEWLINE\n                | NEWLINE IDENTstrparam : STRING\n            | STRING NEWLINE\n            | NEWLINE STRINGnumparam : NUMBER\n            | NUMBER NEWLINE\n            | NEWLINE NUMBER'
    
_lr_action_items = {'DEF':([0,9,],[5,5,]),'PREFERENCE':([0,9,],[6,6,]),'DEFINITION':([0,9,],[7,7,]),'MAPPING':([0,9,],[8,8,]),'$end':([1,2,3,4,14,15,16,33,36,37,61,66,],[0,-2,-4,-5,-1,-3,-6,-11,-7,-8,-10,-9,]),'NEWLINE':([1,2,3,4,14,15,16,17,18,19,23,31,32,33,36,37,40,47,52,53,54,55,56,58,59,61,63,64,66,68,69,71,72,73,80,81,82,83,],[9,-2,-4,-5,-1,-3,-6,30,34,-12,38,45,46,-11,-7,-8,30,-13,62,-22,-24,-25,64,62,30,-10,-23,-26,-9,-28,81,-30,82,-21,-27,-29,-31,-14,]),'IDENT':([5,17,30,40,41,49,52,53,54,55,58,59,60,62,63,64,68,71,73,80,81,82,],[10,23,42,23,51,51,51,-22,-24,-25,51,23,70,51,-23,-26,-28,-30,-21,-27,-29,-31,]),'LBRACKET':([6,8,25,39,57,],[11,13,41,49,65,]),'LPAREN':([7,10,20,51,70,],[12,17,35,59,59,]),'SECTION':([11,34,],[20,20,]),'error':([12,13,41,49,52,53,54,55,58,59,60,62,63,64,68,71,73,80,81,82,],[21,22,56,56,56,-22,-24,-25,56,69,72,56,-23,-26,-28,-30,-21,-27,-29,-31,]),'RPAREN':([17,21,23,24,26,27,28,29,31,32,38,42,43,44,45,46,48,50,59,67,],[25,36,-37,39,-33,-34,-35,-36,-40,-43,-38,-39,-42,-45,-41,-44,57,-32,68,80,]),'STRING':([17,30,35,40,59,65,77,84,],[31,43,48,31,31,74,85,74,]),'NUMBER':([17,30,40,59,],[32,44,32,32,]),'RBRACKET':([18,19,22,47,52,53,54,55,58,63,64,68,71,73,74,75,76,80,81,82,83,85,88,89,90,],[33,-12,37,-13,61,-22,-24,-25,66,-23,-26,-28,-30,-21,-18,83,-16,-27,-29,-31,-14,-17,-15,-19,-20,]),'COMMA':([23,24,26,27,28,29,31,32,38,42,43,44,45,46,50,67,74,75,76,85,88,89,90,],[-37,40,-33,-34,-35,-36,-40,-43,-38,-39,-42,-45,-41,-44,-32,40,-18,84,-16,-17,-15,-19,-20,]),'DOT':([51,],[60,]),'INPUT':([65,84,],[77,77,]),'MULTIPLE':([65,84,],[78,78,]),'REQUIRED':([65,84,],[79,79,]),'COLON':([78,79,],[86,87,]),'BOOL':([86,87,],[89,90,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'funcDef':([0,9,],[2,14,]),'prefBlock':([0,9,],[3,15,]),'notNeededBlock':([0,9,],[4,16,]),'sectionblocklist':([11,],[18,]),'sectionblock':([11,34,],[19,47,]),'paramlist':([17,59,],[24,67,]),'param':([17,40,59,],[26,50,26,]),'identparam':([17,40,59,],[27,27,27,]),'strparam':([17,40,59,],[28,28,28,]),'numparam':([17,40,59,],[29,29,29,]),'stmtList':([41,49,],[52,58,]),'stmt':([41,49,52,58,62,],[53,53,63,63,73,]),'functionCall':([41,49,52,58,60,62,],[54,54,54,54,71,54,]),'functionWithObj':([41,49,52,58,62,],[55,55,55,55,55,]),'blockparamlist':([65,],[75,]),'blockparam':([65,84,],[76,88,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program NEWLINE funcDef','program',3,'p_program_funcDef','parsefile.py',7),
  ('program -> funcDef','program',1,'p_program_funcDef','parsefile.py',8),
  ('program -> program NEWLINE prefBlock','program',3,'p_program_block','parsefile.py',18),
  ('program -> prefBlock','program',1,'p_program_block','parsefile.py',19),
  ('program -> notNeededBlock','program',1,'p_program_block','parsefile.py',20),
  ('program -> program NEWLINE notNeededBlock','program',3,'p_program_block','parsefile.py',21),
  ('notNeededBlock -> DEFINITION LPAREN error RPAREN','notNeededBlock',4,'p_notNeededBlock','parsefile.py',31),
  ('notNeededBlock -> MAPPING LBRACKET error RBRACKET','notNeededBlock',4,'p_notNeededBlock','parsefile.py',32),
  ('funcDef -> DEF IDENT LPAREN paramlist RPAREN LBRACKET stmtList RBRACKET','funcDef',8,'p_funcDef','parsefile.py',37),
  ('funcDef -> DEF IDENT LPAREN RPAREN LBRACKET stmtList RBRACKET','funcDef',7,'p_funcDef','parsefile.py',38),
  ('prefBlock -> PREFERENCE LBRACKET sectionblocklist RBRACKET','prefBlock',4,'p_prefBlock','parsefile.py',46),
  ('sectionblocklist -> sectionblock','sectionblocklist',1,'p_sectionblocklist','parsefile.py',50),
  ('sectionblocklist -> sectionblocklist NEWLINE sectionblock','sectionblocklist',3,'p_sectionblocklist','parsefile.py',51),
  ('sectionblock -> SECTION LPAREN STRING RPAREN LBRACKET blockparamlist RBRACKET','sectionblock',7,'p_sectionblock','parsefile.py',59),
  ('blockparamlist -> blockparamlist COMMA blockparam','blockparamlist',3,'p_blockparamlist','parsefile.py',63),
  ('blockparamlist -> blockparam','blockparamlist',1,'p_blockparamlist','parsefile.py',64),
  ('blockparam -> INPUT STRING','blockparam',2,'p_blockparam','parsefile.py',72),
  ('blockparam -> STRING','blockparam',1,'p_blockparam','parsefile.py',73),
  ('blockparam -> MULTIPLE COLON BOOL','blockparam',3,'p_blockparam','parsefile.py',74),
  ('blockparam -> REQUIRED COLON BOOL','blockparam',3,'p_blockparam','parsefile.py',75),
  ('stmtList -> stmtList NEWLINE stmt','stmtList',3,'p_stmtList','parsefile.py',86),
  ('stmtList -> stmt','stmtList',1,'p_stmtList','parsefile.py',87),
  ('stmtList -> stmtList stmt','stmtList',2,'p_stmtList','parsefile.py',88),
  ('stmt -> functionCall','stmt',1,'p_stmt','parsefile.py',106),
  ('stmt -> functionWithObj','stmt',1,'p_stmt','parsefile.py',107),
  ('stmt -> error NEWLINE','stmt',2,'p_stmt_error','parsefile.py',111),
  ('functionCall -> IDENT LPAREN paramlist RPAREN','functionCall',4,'p_functionCall','parsefile.py',116),
  ('functionCall -> IDENT LPAREN RPAREN','functionCall',3,'p_functionCall','parsefile.py',117),
  ('functionCall -> IDENT LPAREN error NEWLINE','functionCall',4,'p_functionCall_error','parsefile.py',124),
  ('functionWithObj -> IDENT DOT functionCall','functionWithObj',3,'p_functionWithObj','parsefile.py',129),
  ('functionWithObj -> IDENT DOT error NEWLINE','functionWithObj',4,'p_functionWithObj_error','parsefile.py',133),
  ('paramlist -> paramlist COMMA param','paramlist',3,'p_paramlist','parsefile.py',138),
  ('paramlist -> param','paramlist',1,'p_paramlist','parsefile.py',139),
  ('param -> identparam','param',1,'p_param','parsefile.py',147),
  ('param -> strparam','param',1,'p_param','parsefile.py',148),
  ('param -> numparam','param',1,'p_param','parsefile.py',149),
  ('identparam -> IDENT','identparam',1,'p_identparam','parsefile.py',153),
  ('identparam -> IDENT NEWLINE','identparam',2,'p_identparam','parsefile.py',154),
  ('identparam -> NEWLINE IDENT','identparam',2,'p_identparam','parsefile.py',155),
  ('strparam -> STRING','strparam',1,'p_strparam','parsefile.py',162),
  ('strparam -> STRING NEWLINE','strparam',2,'p_strparam','parsefile.py',163),
  ('strparam -> NEWLINE STRING','strparam',2,'p_strparam','parsefile.py',164),
  ('numparam -> NUMBER','numparam',1,'p_numparam','parsefile.py',171),
  ('numparam -> NUMBER NEWLINE','numparam',2,'p_numparam','parsefile.py',172),
  ('numparam -> NEWLINE NUMBER','numparam',2,'p_numparam','parsefile.py',173),
]
